/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author usama
 */
public class RePage extends javax.swing.JFrame {

    /**
     * Creates new form ResgistrationPage
     */
    public RePage() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPinRegistrationPage = new javax.swing.JTextField();
        txtOccupationRegistrationPage = new javax.swing.JTextField();
        txtPhoneRegistrationPage = new javax.swing.JTextField();
        txtNameRegistrationPage = new javax.swing.JTextField();
        txtFatherNameRegistrationPage = new javax.swing.JTextField();
        btnSubmitRegistrationPage = new javax.swing.JButton();
        btnBackRegistrationPage = new javax.swing.JButton();
        btnResetRegistrationPage = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddressRegistrationPage = new javax.swing.JTextArea();
        txtAccountNumberRegistrationPage = new javax.swing.JTextField();
        cmbEducationRegistrationPage = new javax.swing.JComboBox<>();
        txtDOBRegistrationPage = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(215, 230, 238));
        jLabel1.setText("FATHER NAME:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(215, 230, 238));
        jLabel2.setText("PHONE:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(215, 230, 238));
        jLabel3.setText("NAME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(215, 230, 238));
        jLabel4.setText("ACCOUNT NUM:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(215, 230, 238));
        jLabel5.setText("DATE OF BIRTH:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(215, 230, 238));
        jLabel6.setText("OCCUPATION:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(215, 230, 238));
        jLabel7.setText("EDUCATION:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(215, 230, 238));
        jLabel8.setText("PIN:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(215, 230, 238));
        jLabel9.setText("ADDRESS:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        txtPinRegistrationPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtPinRegistrationPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 105, 250, 30));

        txtOccupationRegistrationPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtOccupationRegistrationPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 175, 250, 30));

        txtPhoneRegistrationPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtPhoneRegistrationPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 385, 250, 30));

        txtNameRegistrationPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtNameRegistrationPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 175, 250, 30));

        txtFatherNameRegistrationPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtFatherNameRegistrationPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 245, 250, 30));

        btnSubmitRegistrationPage.setBackground(new java.awt.Color(7, 66, 121));
        btnSubmitRegistrationPage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubmitRegistrationPage.setForeground(new java.awt.Color(215, 230, 238));
        btnSubmitRegistrationPage.setText("SUBMIT");
        btnSubmitRegistrationPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRegistrationPageActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitRegistrationPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        btnBackRegistrationPage.setBackground(new java.awt.Color(7, 66, 121));
        btnBackRegistrationPage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBackRegistrationPage.setForeground(new java.awt.Color(215, 230, 238));
        btnBackRegistrationPage.setText("BACK");
        btnBackRegistrationPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRegistrationPageActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackRegistrationPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, -1, -1));

        btnResetRegistrationPage.setBackground(new java.awt.Color(7, 66, 121));
        btnResetRegistrationPage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnResetRegistrationPage.setForeground(new java.awt.Color(215, 230, 238));
        btnResetRegistrationPage.setText("RESET");
        btnResetRegistrationPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetRegistrationPageActionPerformed(evt);
            }
        });
        jPanel1.add(btnResetRegistrationPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(215, 230, 238));
        jLabel10.setText("REGISTRATION FORM");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        txtAddressRegistrationPage.setColumns(20);
        txtAddressRegistrationPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddressRegistrationPage.setRows(5);
        jScrollPane1.setViewportView(txtAddressRegistrationPage);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 250, 110));

        txtAccountNumberRegistrationPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtAccountNumberRegistrationPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 105, 250, 30));

        cmbEducationRegistrationPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbEducationRegistrationPage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[...Select Education...]", "Matric", "Fsc", "Bachelors", "Masters", "PhD", "MPhil" }));
        jPanel1.add(cmbEducationRegistrationPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 250, -1));

        txtDOBRegistrationPage.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jPanel1.add(txtDOBRegistrationPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 250, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Dashboard.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnBackRegistrationPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRegistrationPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackRegistrationPageActionPerformed

    private void btnResetRegistrationPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetRegistrationPageActionPerformed
        // TODO add your handling code here:
        new RePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnResetRegistrationPageActionPerformed

    private void btnSubmitRegistrationPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRegistrationPageActionPerformed
        Db_Connection1 obj=new Db_Connection1();
        if(txtAccountNumberRegistrationPage.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter an Account Number");
            txtAccountNumberRegistrationPage.grabFocus();
            return;
        }
        else if(txtNameRegistrationPage.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter a Name");
            txtNameRegistrationPage.grabFocus();
            return;
        }
        else if(txtFatherNameRegistrationPage.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter a Father Name");
            txtFatherNameRegistrationPage.grabFocus();
            return;
        }
        else if(txtPhoneRegistrationPage.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter a Phone Number");
            txtPhoneRegistrationPage.grabFocus();
            return;
        }
        else if(txtAddressRegistrationPage.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter an Address");
            txtAddressRegistrationPage.grabFocus();
            return;
        }
        else if(txtDOBRegistrationPage.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter Date Of Birth");
            return;
        }
        else if(txtPinRegistrationPage.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter a Pin");
            txtPinRegistrationPage.grabFocus();
            return;
        }
        else if(cmbEducationRegistrationPage.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Select an Education");
            return;
        }
        else if(obj.searchAccountNumber(txtAccountNumberRegistrationPage.getText())==(Integer.parseInt(txtAccountNumberRegistrationPage.getText()))){
            JOptionPane.showMessageDialog(this, "The entered account number is already registered!");
            txtAccountNumberRegistrationPage.grabFocus();
            return;
        }
        else{
        String Acnum=txtAccountNumberRegistrationPage.getText();
        String ACName=txtNameRegistrationPage.getText();
        String FName=txtFatherNameRegistrationPage.getText();
        String DOB=txtDOBRegistrationPage.getText();
        String Phone=txtPhoneRegistrationPage.getText();
        String Pin=txtPinRegistrationPage.getText();
        String Adrs=txtAddressRegistrationPage.getText();
        String Ocu=txtOccupationRegistrationPage.getText();
        String Edu=cmbEducationRegistrationPage.getSelectedItem().toString();
        int ACNO=Integer.parseInt(Acnum);
        int _Pin=Integer.parseInt(Pin);
        int k=obj.RegisterUser(ACNO,ACName,FName,DOB,Phone,Edu,Adrs,Ocu,_Pin);
             if(k==1){
            JOptionPane.showMessageDialog(this,"SUCESSFULLY REGISTERED!");
            new RePage().setVisible(true);
            dispose();
           }else{
                 JOptionPane.showMessageDialog(this, "Failed to Register!!!");
             }
     
        }
        
    }//GEN-LAST:event_btnSubmitRegistrationPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackRegistrationPage;
    private javax.swing.JButton btnResetRegistrationPage;
    private javax.swing.JButton btnSubmitRegistrationPage;
    private javax.swing.JComboBox<String> cmbEducationRegistrationPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAccountNumberRegistrationPage;
    private javax.swing.JTextArea txtAddressRegistrationPage;
    private javax.swing.JTextField txtDOBRegistrationPage;
    private javax.swing.JTextField txtFatherNameRegistrationPage;
    private javax.swing.JTextField txtNameRegistrationPage;
    private javax.swing.JTextField txtOccupationRegistrationPage;
    private javax.swing.JTextField txtPhoneRegistrationPage;
    private javax.swing.JTextField txtPinRegistrationPage;
    // End of variables declaration//GEN-END:variables
}
